[Redis]
redis = 127.0.0.1:6379

[RedisConfig]
redis.password =
redis.idletimeout = 240
redis.poolsize = 100
redis.db = 0

[MQProxy]
grayMode = false

[KafkaProxy]
enable = true
brokers = 127.0.0.1:9092
sasl = false
user =
password =
;消息失败处理模式，支持retry(重试)/save(保存到redis)/discard(直接丢弃)，默认为retry
failMode = discard