package config

import (
	"errors"
	"log"
	"os"
	"os/user"
	"path/filepath"
	"strings"
	"sync"

	"github.com/kardianos/osext"
)

// Config interface definition
// developers can implement this interface to combine with other config library
type Config interface {
	// get value by section and key,if not exist,return the defaultVal
	MustValue(section, key string, defaultVal ...string) string
	// get value by sction and key and split value by delim,return array
	MustValueArray(section, key, delim string) []string
	// get section value,return array
	GetKeyList(section string) []string
	// get section value,return map
	GetSection(section string) (map[string]string, error)
	// get all section list
	GetSectionList() []string
	// get object value by section
	GetSectionObject(section string, obj interface{}) error
	// set value by section and key when need
	Set(section, key string, value interface{})
}

var (
	// global cache
	// only load the config file once
	// after config init complete,all config data get from cache
	configCache = struct {
		sync.RWMutex
		cache map[string]Config
	}{cache: make(map[string]Config, 0)}

	// when you don't want to use ini or yaml file source,you need the "any" pattern
	// the "any" pattern can customize the data source by register a plugin
	anyFileMap = make(map[string]func() (Config, error), 0)

	// global config
	gCfg Config

	// config path prefix if your config path is not a absolute path
	USER_CONF_PATH string

	configFilename = "../config/app.ini"
)

func SetConfigPath(path string) {
	configFilename = path
	gCfg = nil
}

func InitConfig() {
	// check if config has inited
	if gCfg != nil {
		return
	}

	var configPath string
	var err error

	// set the default path
	if len(configPath) == 0 {
		configPath = configFilename
	}

	// log.Printf("config ini path: %s", configPath)

	// load config from path
	if gCfg, err = Load(configPath); err != nil {
		gCfg = nil
		log.Printf("config error: %v", err)
	}
}

func home() string {
	if usr, err := user.Current(); err == nil {
		return usr.HomeDir
	}
	return "/home/dev"
}

// the default config directory,generated by home()
func Binhome() string {
	if len(USER_CONF_PATH) > 0 {
		return USER_CONF_PATH
	}
	if path, err := osext.ExecutableFolder(); err == nil {
		if strings.HasPrefix(path, "/tmp/go-build") {
			return home() + "/config/"
		}
		return path
	} else {
		return "."
	}
}

// get current path
func pwd() string {
	if path, err := os.Getwd(); err == nil {
		return path
	}

	return ""
}

// get app runtime path
func getAppDir() string {
	if path, err := osext.Executable(); err == nil {
		return filepath.Dir(path)
	}

	return ""
}

func SetConfPathPrefix(fullPathPrefix string) {
	if len(fullPathPrefix) != 0 {
		USER_CONF_PATH = fullPathPrefix
	}
}

func Set(section, key string, value interface{}) {
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", section, key)
		return
	}
	gCfg.Set(section, key, value)
}

func Load(path string) (cfg Config, err error) {
	// load any module
	// path is not a valid path
	if !strings.Contains(path, "/") {
		fn := anyFileMap[path]
		cfg, err = fn()
		return
	}

	if len([]byte(path)) < 4 {
		return nil, errors.New("path invalid")
	}

	// default load module
	fileType := "ini"

	if path[len(path)-4:] == "yaml" {
		fileType = "yaml"
		// if the path suffix is not ".ini", completed path by append ".ini"
	} else if path[len(path)-4:] != ".ini" {
		path = path + ".ini"
	}
	// config cache
	var ok bool
	configCache.RLock()
	// read cache first
	cfg, ok = configCache.cache[path]
	configCache.RUnlock()
	// no cache
	if !ok {
		oPath := path

		// path invalid,path completed
		if !strings.HasPrefix(path, "/") {
			pathsToTry := []string{
				// Binhome() + "/" + oPath,
				// home() + "/" + oPath,
				getAppDir() + "/" + filepath.Base(oPath),
				getAppDir() + "/" + oPath,
				filepath.Dir(getAppDir()) + "/" + oPath,
				pwd() + "/" + oPath,
			}

			for _, potentialPath := range pathsToTry {
				if _, err := os.Stat(potentialPath); err == nil {
					path = potentialPath
					break
				}
			}
		}

		// load file and create cache
		configCache.Lock()
		if fileType == "yaml" {
			if cfg, err = loadYamlFile(path); err == nil {
				configCache.cache[path] = cfg
				log.Printf("load configuration file path: %s", strings.Replace(path, "/./", "/", -1))
			}
		} else {
			if cfg, err = loadIniFile(path); err == nil {
				configCache.cache[path] = cfg
				log.Printf("load configuration file path: %s", strings.Replace(path, "/./", "/", -1))
			}
		}

		configCache.Unlock()
	}
	return
}

func ClearConfigCache() {
	configCache.Lock()
	configCache.cache = make(map[string]Config, 0)
	gCfg = nil
	configCache.Unlock()
}

func GetConf(sec, key string) string {
	// init
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", sec, key)
		return ""
	}
	// if value not existed return ""
	return gCfg.MustValue(sec, key, "")
}

func GetConfDefault(sec, key, def string) string {
	// init
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", sec, key)
		return ""
	}
	// if value not existed return def
	return gCfg.MustValue(sec, key, def)
}

func GetConfArr(sec, key string) []string {
	// init
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", sec, key)
		return []string{}
	}

	// if value not existed return " "
	return gCfg.MustValueArray(sec, key, " ")
}

func GetConfStringMap(sec string) (ret map[string]string) {
	// init
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s]", sec)
		return nil
	}

	var err error
	// if value not existed return empty map
	if ret, err = gCfg.GetSection(sec); err != nil {
		log.Printf("config,err:%v", err)
		ret = make(map[string]string, 0)
	}

	return
}

func GetConfArrayMap(sec string) (ret map[string][]string) {
	// init
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s]", sec)
		return nil
	}
	ret = make(map[string][]string, 0)
	// get all keys
	confs := gCfg.GetKeyList(sec)
	// get all config by range keys
	for _, k := range confs {
		ret[k] = gCfg.MustValueArray(sec, k, " ")
	}

	return
}

func ConfMapToStruct(sec string, v interface{}) error {
	// init
	InitConfig()
	if gCfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s]", sec)
		return nil
	}

	return gCfg.GetSectionObject(sec, v)
}
