package config

import (
	"errors"
	"log"
	"os"
	"os/user"
	"path/filepath"
	"strings"
	"sync"

	"github.com/kardianos/osext"
)

// Config interface definition
// developers can implement this interface to combine with other config library
type Config interface {
	// get value by section and key,if not exist,return the defaultVal
	MustValue(section, key string, defaultVal ...string) string
	// get value by sction and key and split value by delim,return array
	MustValueArray(section, key, delim string) []string
	// get section value,return array
	GetKeyList(section string) []string
	// get section value,return map
	GetSection(section string) (map[string]string, error)
	// get all section list
	GetSectionList() []string
	// get object value by section
	GetSectionObject(section string, obj interface{}) error
	// set value by section and key when need
	Set(section, key string, value interface{})
}

var (
	// global cache
	// only load the config file once
	// after config init complete,all config data get from cache
	configCache = struct {
		sync.RWMutex
		cache map[string]Config
	}{cache: make(map[string]Config, 0)}

	// when you don't want to use ini or yaml file source,you need the "any" pattern
	// the "any" pattern can customize the data source by register a plugin
	anyFileMap = make(map[string]func() (Config, error), 0)

	// gCfgMu 保护 gCfg 和 configFilename 的并发读写
	gCfgMu sync.RWMutex

	// global config
	gCfg Config

	// config path prefix if your config path is not a absolute path
	USER_CONF_PATH string

	configFilename = "../config/app.ini"
)

func SetConfigPath(path string) {
	gCfgMu.Lock()
	configFilename = path
	gCfg = nil
	gCfgMu.Unlock()
}

func InitConfig() {
	// 快路径：已初始化
	gCfgMu.RLock()
	if gCfg != nil {
		gCfgMu.RUnlock()
		return
	}
	gCfgMu.RUnlock()

	// 升级为写锁，double-check 后再执行初始化
	gCfgMu.Lock()
	defer gCfgMu.Unlock()
	if gCfg != nil {
		return
	}

	configPath := configFilename
	var err error
	if gCfg, err = Load(configPath); err != nil {
		gCfg = nil
		log.Printf("config error: %v", err)
	}
}

func home() string {
	if usr, err := user.Current(); err == nil {
		return usr.HomeDir
	}
	return "/home/dev"
}

// the default config directory,generated by home()
func Binhome() string {
	if len(USER_CONF_PATH) > 0 {
		return USER_CONF_PATH
	}
	if path, err := osext.ExecutableFolder(); err == nil {
		if strings.HasPrefix(path, "/tmp/go-build") {
			return home() + "/config/"
		}
		return path
	} else {
		return "."
	}
}

// get current path
func pwd() string {
	if path, err := os.Getwd(); err == nil {
		return path
	}

	return ""
}

// get app runtime path
func getAppDir() string {
	if path, err := osext.Executable(); err == nil {
		return filepath.Dir(path)
	}

	return ""
}

func SetConfPathPrefix(fullPathPrefix string) {
	if len(fullPathPrefix) != 0 {
		USER_CONF_PATH = fullPathPrefix
	}
}

// globalCfg 在锁保护下返回当前全局配置，供 Get* 系列统一使用
func globalCfg() Config {
	gCfgMu.RLock()
	defer gCfgMu.RUnlock()
	return gCfg
}

func Set(section, key string, value interface{}) {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", section, key)
		return
	}
	cfg.Set(section, key, value)
}

func Load(path string) (cfg Config, err error) {
	// load any module
	// path is not a valid path
	if !strings.Contains(path, "/") {
		fn := anyFileMap[path]
		if fn == nil {
			err = errors.New("unknown config source: " + path)
			return
		}
		cfg, err = fn()
		return
	}

	if len(path) < 2 {
		return nil, errors.New("path invalid")
	}

	// 用 filepath.Ext 检测文件类型，支持 .yaml / .yml / .ini
	fileType := "ini"
	switch strings.ToLower(filepath.Ext(path)) {
	case ".yaml", ".yml":
		fileType = "yaml"
	case ".ini":
		// 已是 ini，无需处理
	default:
		// 无扩展名或未知扩展名，补 .ini 后缀
		path = path + ".ini"
	}
	// config cache
	var ok bool
	configCache.RLock()
	// read cache first
	cfg, ok = configCache.cache[path]
	configCache.RUnlock()
	// no cache
	if !ok {
		oPath := path

		// path invalid,path completed
		if !strings.HasPrefix(path, "/") {
			pathsToTry := []string{
				// Binhome() + "/" + oPath,
				// home() + "/" + oPath,
				getAppDir() + "/" + filepath.Base(oPath),
				getAppDir() + "/" + oPath,
				filepath.Dir(getAppDir()) + "/" + oPath,
				pwd() + "/" + oPath,
			}

			for _, potentialPath := range pathsToTry {
				if _, err := os.Stat(potentialPath); err == nil {
					path = potentialPath
					break
				}
			}
		}

		// load file and create cache
		configCache.Lock()
		// double-check：升级为写锁期间可能已被其他 goroutine 加载
		if cached, exists := configCache.cache[path]; exists {
			configCache.Unlock()
			cfg = cached
			return
		}
		if fileType == "yaml" {
			if cfg, err = loadYamlFile(path); err == nil {
				configCache.cache[path] = cfg
				log.Printf("load configuration file path: %s", strings.Replace(path, "/./", "/", -1))
			}
		} else {
			if cfg, err = loadIniFile(path); err == nil {
				configCache.cache[path] = cfg
				log.Printf("load configuration file path: %s", strings.Replace(path, "/./", "/", -1))
			}
		}

		configCache.Unlock()
	}
	return
}

func ClearConfigCache() {
	configCache.Lock()
	configCache.cache = make(map[string]Config, 0)
	configCache.Unlock()

	gCfgMu.Lock()
	gCfg = nil
	gCfgMu.Unlock()
}

func GetConf(sec, key string) string {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", sec, key)
		return ""
	}
	return cfg.MustValue(sec, key, "")
}

func GetConfDefault(sec, key, def string) string {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", sec, key)
		return ""
	}
	return cfg.MustValue(sec, key, def)
}

func GetConfArr(sec, key string) []string {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s,key:%s]", sec, key)
		return []string{}
	}
	return cfg.MustValueArray(sec, key, " ")
}

func GetConfStringMap(sec string) (ret map[string]string) {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s]", sec)
		return nil
	}
	var err error
	if ret, err = cfg.GetSection(sec); err != nil {
		log.Printf("config,err:%v", err)
		ret = make(map[string]string, 0)
	}
	return
}

func GetConfArrayMap(sec string) (ret map[string][]string) {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		log.Printf("config error: NOT_FOUND[sec:%s]", sec)
		return nil
	}
	ret = make(map[string][]string, 0)
	for _, k := range cfg.GetKeyList(sec) {
		ret[k] = cfg.MustValueArray(sec, k, " ")
	}
	return
}

func ConfMapToStruct(sec string, v interface{}) error {
	InitConfig()
	cfg := globalCfg()
	if cfg == nil {
		return errors.New("config not initialized")
	}
	return cfg.GetSectionObject(sec, v)
}
